[package]
name = "elfutils"
version = "0.0.1"
license = "MIT/Apache-2.0"
authors = ["Josh Stone <jistone@redhat.com>"]
repository = "https://github.com/cuviper/elfutils-rs"
description = "Placeholder for bindings to elfutils"

[dependencies]

[dependencies.libdw]
optional = false
path = "libdw"
version = "0.0.1"

[dependencies.libdwelf]
optional = false
path = "libdwelf"
version = "0.0.1"

[dependencies.libdwfl]
optional = false
path = "libdwfl"
version = "0.0.1"

[dependencies.libelf]
optional = false
path = "libelf"
version = "0.0.1"
