[package]
authors = ["Josh Stone <jistone@redhat.com>"]
description = "Bindings to elfutils"
license = "MIT/Apache-2.0"
name = "libelf"
repository = "https://github.com/cuviper/elfutils-rs"
version = "0.0.3"
include = ["Cargo.toml", "src/**/*.rs"]

[dependencies]

[dependencies.libelf-sys]
optional = false
path = "../libelf-sys"
version = "0.0.2"
