[package]
name = "libdw-sys"
version = "0.0.1"
license = "MIT/Apache-2.0"
authors = ["Josh Stone <jistone@redhat.com>"]
repository = "https://github.com/cuviper/elfutils-rs"
build = "build.rs"
description = "Placeholder for bindings to elfutils"

[build-dependencies]
pkg-config = "0.3.8"

[dependencies]
libc = "0.2.16"

[dependencies.libelf-sys]
optional = false
path = "../libelf-sys"
